version: '3.1'

services:
  web:
    build: .
    container_name: php-apache
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
    ports:
      - "${APACHE_PORT}:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    platform: linux/arm64/v8
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
